### ISSUE TITLE
Changelog would be nice

### ISSUE THREAD

**Issue by icemac** [henry0312/pytest-docstyle#55]
Having a change log in the repository would be nice to see what to change when upgrading e. g. from 1.5 to 2.0.

Without the change log everybody who is already using this package has to go though the commits to find the relevant changes in the configuration to use the new version.

**Comment by henry0312** [comment]
You can check change logs in https://github.com/henry0312/pytest-docstyle/releases.

**Comment by icemac** [comment]
Thank you for pointing me to this place. Sorry for not poking around enough to find it by myself.

**Comment by henry0312** [comment]
Don’t worry about it :)
